//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Student
    {
        [Display(Name = "Student Id")]
        public int StudentId { get; set; }

        [Display(Name = "Student Name")]
        [Required]
        public string StudentName { get; set; }

        [Display(Name = "Student Email")]
        [Required]
        [EmailAddress]
        public string StudentEmail { get; set; }

        [Display(Name = "Student Phone no.")]
        [MinLength(10)]
        [MaxLength(10)]
        public string StudentMobile { get; set; }

        [Display(Name = "Gender")]
        [Required]
        public string Gender { get; set; }

        [Display(Name = "Date of birth")]
        [Required]
        [DisplayFormat(DataFormatString = "{0:d}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> StudentDoB { get; set; }

        [Display(Name = "Age")]
        public Nullable<int> StudentAge { get
            /*{
                DateTime now = DateTime.Today;
                int age = now.Year - StudentDoB.Value.Year;
                if (StudentDoB > now.AddYears(-age)) age--;
                return age;
            }*/; set; }

        [Display(Name = "Address")]
        [Required]
        public string Address { get; set; }

        [Display(Name = "Course")]
        [Required]
        public int CourseId { get; set; }

        [Display(Name = "Joining Date")]
        [Required]
        [DisplayFormat(DataFormatString = "{0:d}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> JoiningDate { get; set; }

        [Display(Name = "Current Status")]
        [Required]
        public Nullable<int> StatusCode { get; set; }

        public Nullable<int> ParentId { get; set; }
    
        public virtual Cours Cours { get; set; }
        public virtual Parent Parent { get; set; }
        public virtual Status Status { get; set; }
    }
}
