//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int StudentId { get; set; }
        public string StudentName { get; set; }
        public string StudentEmail { get; set; }
        public string StudentMobile { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> StudentDoB { get; set; }
        public Nullable<int> StudentAge { get; set; }
        public string Address { get; set; }
        public int CourseId { get; set; }
        public Nullable<System.DateTime> JoiningDate { get; set; }
        public Nullable<int> StatusCode { get; set; }
        public Nullable<int> ParentId { get; set; }
    
        public virtual Cours Cours { get; set; }
        public virtual Parent Parent { get; set; }
        public virtual Status Status { get; set; }
    }
}
